// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
// defineApp
export { defineApp } from './core/defineApp'
export type { RuntimeConfig } from './core/defineApp'
// plugins
export { StyleSheetManager, ThemeProvider, createGlobalStyle, css, keyframes, styled, useTheme } from '/Users/shenck/RRWeb-client/projects/playground/src/.umi/plugin-styledComponents';
// plugins types.d.ts
// @umijs/renderer-*
export { createBrowserHistory, createHashHistory, createMemoryHistory, Helmet, HelmetProvider, createSearchParams, generatePath, matchPath, matchRoutes, Navigate, NavLink, Outlet, resolvePath, useLocation, useMatch, useNavigate, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams, useAppData, useClientLoaderData, useLoaderData, useRouteProps, useSelectedRoutes, useServerLoaderData, renderClient, __getRoot, Link, useRouteData, __useFetcher, withRouter } from '/Users/shenck/RRWeb-client/node_modules/.pnpm/@umijs+renderer-react@4.5.1_nnrd3gsncyragczmpvfhocinkq/node_modules/@umijs/renderer-react';
export type { History, ClientLoader } from '/Users/shenck/RRWeb-client/node_modules/.pnpm/@umijs+renderer-react@4.5.1_nnrd3gsncyragczmpvfhocinkq/node_modules/@umijs/renderer-react'
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from '/Users/shenck/RRWeb-client/node_modules/.pnpm/umi@4.5.1_2v72zxohamkzk34nbnmsdu5jpy/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
// react ssr
export const useServerInsertedHTML: Function = () => {};
// test
export { TestBrowser } from './testBrowser';
