// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","id":"1"},"2":{"path":"/","parentId":"1","id":"2"},"3":{"path":"/form","parentId":"1","id":"3"},"4":{"path":"/replay","parentId":"1","id":"4"},"5":{"path":"*","parentId":"1","id":"5"}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "layouts__basic__index" */'@/layouts/basic/index.tsx')),
'2': React.lazy(() => import(/* webpackChunkName: "p__index" */'@/pages/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__form" */'@/pages/form.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__replay" */'@/pages/replay.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__404" */'@/pages/404.tsx')),
},
  };
}
